### ISSUE TITLE
no audio unless toggle ndi output

### ISSUE THREAD

**Issue by droopified** [DistroAV/DistroAV#298] opened 2019-03-25 17:41 UTC
i get no audio on the 2nd system unless i go to the main system and disable and reneable the ndi output. if i go live AFTER doing this, i have to do it again. anyway to fix this?

**Comment by Trouffman** [comment] 2024-06-10 08:25
Old issue, expected to be fixed in v6.
See #1027 for details

**Comment by paulpv** [comment] 2024-07-21 06:11
Closing dupe of #429

**Closed by paulpv** 2024-07-21 06:11 UTC
Labels: incomplete, needs-investigation
