### ISSUE TITLE
BirdDog PF120 NDI-5.5 Camera doesn't work in OBS-NDI?

### ISSUE THREAD

**Issue by Jaxel** [DistroAV/DistroAV#854] opened 2023-02-28 14:36 UTC
Haven't streamed in a year... now setting everything back up and I can't get my camera working.

BirdDog PF120 NDI-5.5.089
OBS 29.0.2 64-bit
OBS-NDI 4.10
NDI Runtime 5.5.2.0

Camera shows up perfectly fine in both NDI Tools and BirdDog Cam Control. Does not show up in OBS.

I also tried NDI Runtime 5.0.10.1 without any changes.

**Comment by Jaxel** [comment] 2023-02-28 14:43
I've got an update!

I uninstalled NDI Tools and the NDI Runtime 5.5.2.0...

I then installed NDI Analysis BETA which came with the 5.5.3.0 Runtime.

Now, my camera is working great in OBS. HOWEVER, OBS gives me the "NDI Runtime not found" error when starting up.

**Comment by Jaxel** [comment] 2023-02-28 14:59
And after restarting OBS once... it stopped working. The video properties in OBS probably unselected the camera; and since I can't access the video properties to reselect it, it's done.

**Comment by paulpv** [comment] 2023-03-01 02:54
@Jaxel Have you tried w/ the 4.11.0-RC build?

**Comment by Trouffman** [comment] 2023-03-02 11:42
@Jaxel Is your camera using multicast or rTCP int he settings?

If you can do a full reset of the camera - confirm the protocol settings as well. (could be that the camera is using an NDI 5 specific thing that is not yet implemented in OBS-NDI).
> If you have a Birddog Quad to test > try to get the camera feed to output on the quad (AFAIK they are still on the 4.x SDK there)

**Comment by Jaxel** [comment] 2023-03-02 14:57
Tried TCP, Multicast, UDP and rUDP. Made no difference.

Full reset made no difference.

**Comment by Trouffman** [comment] 2023-03-02 16:00
Noted.

If your run the NDI Tools "test patterns"bon another system on that network, can you see it in both studio monitor and OBS ?

If not in OBS > Check your firewall rules, maybe OBS is missing access :D

To test : disable firewall. Test. If it works, then add the OBS to the lost of allowed app in both your local and public network type.

**Comment by Jaxel** [comment] 2023-03-02 16:53
It's not a firewall issue.

**Comment by Trouffman** [comment] 2023-03-02 17:19
Did you run the test as outlined ? +Sorry to bother checking)

**Comment by Jaxel** [comment] 2023-03-02 17:44
Yes.

**Comment by paulpv** [comment] 2023-03-03 09:03
I have zero experience with hardware [other than a PC/Pi/Nano] that supports NDI.

If BirdDog or anyone else wanted to sent me a few test devices I would be glad to see what I can do.

Otherwise this plugin may have to rely on some other coder out there with access to the hardware to hack at this code to get it to work and submit a PR.

**Comment by Trouffman** [comment] 2023-03-03 09:56
Indeed I could reproduce the bug here with a Birddog SDI 4K SDI. Looking into the debug.

**Comment by Trouffman** [comment] 2023-03-03 10:21
And obviously when I want to debug, this worked....

### Test done on :
- OBS 29.0.2
- OBS-NDI 4.11.0
- NDI Runtime 5.5.3.0
- Clean scene collection
 
### OBS-NDI startup log 
`10:58:32.313: [obs-ndi] obs_module_load: hello ! (version 4.11.0)
10:58:32.313: [obs-ndi] load_ndilib: Trying 'C:/Program Files/NDI/NDI 5 Runtime/v5/Processing.NDI.Lib.x64.dll'
10:58:32.313: [obs-ndi] load_ndilib: Found NDI library at 'C:/Program Files/NDI/NDI 5 Runtime/v5/Processing.NDI.Lib.x64.dll'
10:58:32.317: [obs-ndi] load_ndilib: NDI runtime loaded successfully
10:58:32.317: [obs-ndi] load_ndilib: NDIlib_v5_load found
10:58:32.327: [obs-ndi] obs_module_load: NDI library initialized successfully (NDI SDK WIN64 11:14:50 Feb  2 2023 5.5.3.0)`

### Test & results :
##Test 1
- Load OBS.
- add new source > NDI 
Settings : 
- Bandwidth : highest
- Sync : Source Timing
- hardware acceleration : no
- latency : Normal
![image](https://user-images.githubusercontent.com/2151317/222691305-0e5a7e77-a98b-49b1-96a2-6dd8685cbc5a.png)

##Result: WORKS
![image](https://user-images.githubusercontent.com/2151317/222691643-132a3f87-d5bc-425d-b7b5-257899b1abf6.png)


## Log for the test 1: 
`10:58:34.097: ==== Startup complete ===============================================
10:58:34.182: All scene data cleared
10:58:34.182: ------------------------------------------------
10:58:34.200: Switched to scene 'Scene'
10:58:34.200: ------------------------------------------------
10:58:34.200: Loaded scenes:
10:58:34.200: - scene 'Scene':
10:58:34.200: ------------------------------------------------
11:01:23.593: started A/V threads for source ''
11:01:23.594: A/V thread for 'NDI Test Source' started
11:01:23.601: User added source 'NDI Test Source' (ndi_source) to scene 'Scene'
11:02:36.927: audio thread for 'NDI Test Source' completed
11:02:36.934: started A/V threads for source 'BD-VENUE (Slides)'
11:02:36.934: A/V thread for 'NDI Test Source' started
`

###Test 2:
Same as Test 1
Sync: Network

Result : works too.

### Test 3
- Tested all the other combination of sync / bandwidth, hardware acceleration and latency mode. -> all work (+tally is working too in the studio monitor = you can see when the feed is accessed)


This is weird, as the firs ttime I loaded it it did not work.

### NDI Analysis tool report
`C:\Program Files\NDI\NDI 5 Analysis BETA\x64>NDIAnalysis.exe /source:"BD-VENUE (Slides)" /time:10
NDI Analysis BETA v5.5.3.0
Copyright (C)2014-2023, NewTek, inc.

NDI version : 5.5.3.0

11:16:04.080: Video receiver creation succeeded.
11:16:04.080: Audio receiver creation succeeded.
11:16:08.085: Video connection opened.
11:16:08.085: Audio connection opened.
11:16:08.099: Source is using NDI 4.5.3 on the LINUX platform.
11:16:08.099: Capabilities, Web interface=http://192.168.100.100/
11:16:08.099: Tally program=false preview=false
11:16:08.099: Product, Long name=BirdDog Australia 4K Converter
11:16:08.099: Product, Short name=4K Converter
11:16:08.099: Product, Model=BirdDog 4K SDI
11:16:08.099: Product, Manufacturer=BirdDog Australia
11:16:08.099: Product, Version=BirdDog 4K SDI 4.5.198-LTS(BETA)-DecDebug
11:16:09.149: Video format changed. 1920x1080, codec=SpeedHQ Mode 2, progressive, aspect ratio=1.78, frame-rate=29.97, no alpha channel.
11:16:14.091: Video data rate (Mbps). Avg=0.28
11:16:14.091: Video size (KB). Min=168.89 Avg=168.89 +/- 0.00 Max=168.89
11:16:19.099: Video data rate (Mbps). Avg=0.28
11:16:19.099: Video size (KB). Min=168.89 Avg=168.89 +/- 0.00 Max=168.89
11:16:19.099: Video recv (ms). Min=5008.26 Avg=5008.26 +/- 0.00 Max=5008.26
11:16:19.099: Video send (ms). Min=5008.94 Avg=5008.94 +/- 0.00 Max=5008.94
11:16:19.100: Video connection closed.
11:16:19.101: Video receiver destroyed.
11:16:19.102: Audio connection closed.
11:16:19.110: Audio receiver destroyed.`

> The Birddog SDI 4K is still using the old SDK 4.5.x I suspect the Camera is on NDI which means, it is using feature not yet implements in this project. (this is a major undertaking & ongoing atm.)

@Jaxel Please run the following and provide the feedback.

- Get NDI Analysis Tool : https://ndi.tv/tools/
- On the same PC as the OBS search for it with command : 
NDIAnalysis.exe /find /time:5

- Find the part wehert you have your camera name
`>NDIAnalysis.exe /find /time:5
NDI Analysis BETA v5.5.3.0
Copyright (C)2014-2023, NewTek, inc.

NDI version : 5.5.3.0

Searching for NDI sources ... (3 found)
  1: name="A2-PC1 (OBS Output)"
     host="192.168.22.114"
     port="5961"
     type="NDI"
  2: name="BD-VENUE (Slides)"
     host="192.168.100.100"
     port="5962"
     type="NDI"`

- Run the diagnosis on your camera
`NDIAnalysis.exe /source:"The value you got just before" /time:10`

Thanks!

**Comment by Trouffman** [comment] 2023-03-03 10:37
Note  pretty much all of the Birddog cameras are now using the NDI 5 SDK > so i strongly suspect this is using an NDI5-only feature somewhere and thus OBS-NDI cannot read from it...

**Comment by Jaxel** [comment] 2023-03-04 17:59
```
NDIAnalysis.exe /source:"BIRDDOG-151B9 (CAM)" /time:10
NDI Analysis BETA v5.5.3.0
Copyright (C)2014-2023, NewTek, inc.

NDI version : 5.5.3.0

12:58:44.686: Video receiver creation succeeded.
12:58:44.686: Audio receiver creation succeeded.
12:58:48.689: Video connection opened.
12:58:48.689: Audio connection opened.
12:58:48.694: Source is using NDI 5.5.2 on the LINUX platform.
12:58:48.694: Capabilities, PTZ control=true
12:58:48.694: Capabilities, PTZ control (pan, tilt control)=true
12:58:48.694: Capabilities, PTZ control (zoom control)=true
12:58:48.694: Capabilities, PTZ control (iris control)=true
12:58:48.695: Capabilities, PTZ control (white balance)=true
12:58:48.695: Capabilities, PTZ control (exposure control)=true
12:58:48.695: Capabilities, PTZ control (focus control)=true
12:58:48.695: Capabilities, PTZ control (autofocus support)=true
12:58:48.695: Capabilities, PTZ control (preset speed support)=true
12:58:48.695: Capabilities, Web interface=http://192.168.1.15/
12:58:48.695: Product, Long name=BirdDog Australia Camera
12:58:48.695: Product, Short name=Camera
12:58:48.695: Product, Model=BirdDog PF120
12:58:48.695: Product, Manufacturer=BirdDog Australia
12:58:48.695: Product, Version=BirdDog PF120 5.5.094
12:58:48.703: Video format changed. 1920x1080, codec=SpeedHQ Mode 2, progressive, aspect ratio=1.78, frame-rate=59.94, no alpha channel.
12:58:49.692: Video data rate (Mbps). Avg=126.68
12:58:49.692: Video size (KB). Min=253.75 Avg=254.72 +/- 0.44 Max=255.73
12:58:49.692: Video recv (ms). Min=15.87 Avg=16.67 +/- 0.53 Max=17.69
12:58:49.692: Video send (ms). Min=2.06 Avg=16.92 +/- 13.80 Max=31.37
12:58:54.697: Video data rate (Mbps). Avg=126.35
12:58:54.697: Video size (KB). Min=253.70 Avg=256.78 +/- 0.69 Max=257.84
12:58:54.697: Video recv (ms). Min=15.72 Avg=16.69 +/- 0.53 Max=17.96
12:58:54.697: Video send (ms). Min=2.17 Avg=16.68 +/- 13.49 Max=31.33
12:58:59.701: Video data rate (Mbps). Avg=126.38
12:58:59.701: Video size (KB). Min=255.46 Avg=256.71 +/- 0.50 Max=257.88
12:58:59.701: Video recv (ms). Min=15.40 Avg=16.68 +/- 0.57 Max=18.37
12:58:59.701: Video send (ms). Min=2.16 Avg=16.68 +/- 13.56 Max=31.27
12:58:59.701: Video connection closed.
12:58:59.701: Video receiver destroyed.
12:58:59.701: Audio connection closed.
12:59:01.597: Audio receiver destroyed.
```

**Comment by Trouffman** [comment] 2023-03-06 08:26
Any chance you could do a screen recording reproducting of the problem ?  (loom.com or another OBS)

Thinking about it... please confirm that when you test you have:
- only one source in OBS
- Source is "visible"
- right-click on source, transform > Reset transform
- right-click on source, transform > Fit to screen
- NDI source option > bandwidth : highest

Thanks

**Comment by Jaxel** [comment] 2023-03-07 15:34
Screen recording is pointless. The dropdown list for "Source Name" on adding an NDI source is empty.

**Comment by paulpv** [comment] 2023-03-07 16:39
> The dropdown list for "Source Name" on adding an NDI source is empty.

What OS are you running?
Is your firewall set to allow OBS or NDI?

**Comment by Jaxel** [comment] 2023-03-07 17:11
This is not an OS or NDI issue. This is an OBS issue not handling NDI 5.5. The camera shows up in all other NDI applications; just not OBS. The camera worked perfectly fine last year when it was still running the NDI 4 firmware.

Windows 10 22H2
And yes on firewall.

**Comment by paulpv** [comment] 2023-03-07 17:21
obs-ndi uses NDI 5.5.3 runtime, so should handle NDI 5.5 devices fine.

**Comment by paulpv** [comment] 2023-03-07 17:51
@Jaxel I wrote this test/demo app a few months ago that might help to debug:
* https://github.com/NightVsKnight/QtNdiMonitorCapture

Let me brush it off and get it to build and we could use that as a baseline test if a 3rd party app using your installed NDI 5.x runtime can see NDI sources on your PC or not.

**Comment by Jaxel** [comment] 2023-03-07 18:42
The camera randomly just started working... Don't know why. Constantly uninstalling and reinstalling drivers managed to flip the right magic switch to get it working.

**Comment by paulpv** [comment] 2023-03-07 22:09
> The camera randomly just started working... Don't know why. Constantly uninstalling and reinstalling drivers managed to flip the right magic switch to get it working.

That is [almost entirely] fantastic news! :)

Odd about it being so difficult to install.

I'll see what improvements we can make here to make it more reliable.

Thank you very much for persisting and sticking through it to get it running!

Can this runtime Issue be closed?

Since I don't know the specific install problem your PC was having I don't really have anything to write up a new install Issue other than just a general reliability of the install and NDI runtime which is admittedly a bit of a mess, especially since not even the NDI runtime is currently downloadable.

I am tempted to close this Issue; let me know if you disagree and what specific action we can take here.

**Comment by paulpv** [comment] 2023-03-08 06:22
@Jaxel FYI, my NDI test/demo app is now available at:
https://github.com/NightVsKnight/QtNdiMonitorCapture/releases/tag/0.0.1

Feel free to try that out and let me know if it more reliably sees any NDI sources better than the OBS-NDI plugin.

**Closed** 2024-12-04 19:01 UTC
