### ISSUE TITLE
[Bug]: obs-ndi.so missing after installation on Debian 12 (bookworm)

### ISSUE THREAD

**Issue by johnedstone** [DistroAV/DistroAV#1167] opened 2024-12-19 02:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a similar issue

### This bug exists on the latest available release of DistroAV and supported environment?

- [X] I have checked this bug still exist on the latest available version of DistroAV
- [X] I have checked that my OS / OBS / NDI versions are supported

### OBS Log [URL] - Important!

https://obsproject.com/logs/FoSlJ36Qn7wfOq6I

### Issue reported - Current Behavior

After following the installation at [https://github.com/DistroAV/DistroAV/wiki/1.-Installation](https://github.com/DistroAV/DistroAV/wiki/1.-Installation) obs-ndi.so is not installed

### Expected Behavior

I expect obs-ndi.so to be in the plugins directory and then show up in OBS when selecting a source

### Steps To Reproduce

NDI sources does not show up when I add a Source

I suspect the issue is that there is no obs-ndi.so.
Where is this suppose to come from?
```
$ ls /usr/lib/x86_64-linux-gnu/obs-plugins/
decklink-captions.so   decklink.so  frontend-tools.so  linux-alsa.so     linux-jack.so      linux-pulseaudio.so  obs-ffmpeg     obs-filters.so  obs-transitions.so  obs-x264.so       text-freetype2.so
decklink-output-ui.so  distroav.so  image-source.so    linux-capture.so  linux-pipewire.so  linux-v4l2.so        obs-ffmpeg.so  obs-outputs.so  obs-websocket.so    rtmp-services.so  vlc-video.so

$ ls /usr/share/obs/obs-plugins/
decklink           decklink-output-ui  frontend-tools  linux-alsa     linux-jack      linux-pulseaudio  obs-ffmpeg   obs-outputs      obs-websocket  rtmp-services   vlc-video
decklink-captions  distroav            image-source    linux-capture  linux-pipewire  linux-v4l2        obs-filters  obs-transitions  obs-x264       text-freetype2
```

### Environment

```markdown
- OS:Debian 12
- OBS:obs-studio/stable,now 29.0.2+dfsg-1+b1 amd64 [installed,automatic]
- DistroAV: distroav/now 6.0.0 amd64 [installed,local]
- NDI:

sudo find /usr/ -type f -name '*libndi*' -print
/usr/local/lib/libndi.so.6.1.0
```
```


### Pre-Check for Bug Report

- [X] I am able to reproduce the bug following the steps provided above
- [ ] I have confirmed this bug exist on more than one device/computer
- [ ] I have tested using a new scene collection to reproduce the issue
- [X] I have tested on a 'clean' OBS installation (aka with no other scripts or plugin installed)

**Comment by johnedstone** [comment] 2024-12-19 04:49
Here is a screenshot of the Sources choices. I'm looking for NDI source
![Screenshot from 2024-12-18 23-47-58](https://github.com/user-attachments/assets/6ae6db7b-e304-4799-955d-e6803e866175)

**Comment by johnedstone** [comment] 2024-12-19 04:53
running obs --verbose and grepping for distroav, maybe this is the error:
```
error: os_dlopen(/usr//lib/x86_64-linux-gnu/obs-plugins/distroav.so->/usr//lib/x86_64-linux-gnu/obs-plugins/distroav.so): libobs-frontend-api.so.30: cannot open shared object file: No such file or directory
```

**Comment by johnedstone** [comment] 2024-12-19 05:21
I see 29 is there:
```
$ sudo find /usr/ -type f -name 'libobs*' -print
/usr/lib/x86_64-linux-gnu/libobs.so.29
/usr/lib/x86_64-linux-gnu/libobs-frontend-api.so.29
/usr/lib/x86_64-linux-gnu/libobs-opengl.so.29
/usr/lib/x86_64-linux-gnu/libobsglad.so.29
/usr/lib/x86_64-linux-gnu/libobs-scripting.so.29
```

**Comment by RayneYoruka** [comment] 2024-12-19 05:23
Unsupported OBS version.
![image](https://github.com/user-attachments/assets/961b041b-f3fa-4a2d-8d57-b695c2b215a6)

**Comment by johnedstone** [comment] 2024-12-19 05:23
Ouch, I missed that ... thank you

**Comment by RayneYoruka** [comment] 2024-12-19 05:24
I'll be closing then since it's not a bug.

**Closed by RayneYoruka** 2024-12-19 05:24 UTC
Labels: obs
