### ISSUE TITLE
[Bug]: Audio only source does not stream after OBS restart

### ISSUE THREAD

**Issue by jwineinger** [DistroAV/DistroAV#981] opened 2024-02-18 22:50 UTC
### Operating System Version

macOS Monterey 12.7.2

### CPU

2.5 GHz Quad-Core Intel Core i7

### GPU

AMD Radeon R9 M370X 2 GB, Intel Iris Pro 1536 MB

### NDI Devices

PTZOptics camera

### OBS Version

30.0.2

### OBS Installation Method

dmg

### OBS-NDI Version

4.13.0

### OBS-NDI Installation Method

pkg

### [Extra] Installation Steps

The obs-ndi-4.13.0-macos-universal.pkg seems to install files in /Library/Application Support/obs-studio/plugins/, but my OBS does not find the plugin there, so I have to move the two obs-ndi folders from there to under my ~user/Library/Application Support/obs-studio/plugins/ and change ownership to user (chown -R user:staff obs-ndi*)

### OBS Log [URL]

https://obsproject.com/logs/H33IOGUg8OSJnda7

### NDI Version

5.5.3

### Describe the bug

We have a single audio-only (Bandwidth: Audio Only) NDI source that we share across all scenes in order to prevent "echoing" sources when during a scene transition. I recently updated OBS, obs-ndi, and the NDI SDK. After these updates, audio-only sources seem to only work for the OBS session in which they are created. After OBS restarts, they appear to work (sound levels show activity, etc) but no audio is streamed. The trick of changing the Sync to Network and back to Source Timing that others have mentioned doesn't do anything here.

### Steps to reproduce the problem

1. Add a new NDI source. Set bandwidth to Audio Only
2. Start a stream. All works fine.
3. Restart OBS
4. Start a new stream. No audio

**Comment by Trouffman** [comment] 2024-05-13 22:49
This is a known issue with Audio-Only.
I could not find the main bug to attach it too. but this is on the back log of issues to address

**Comment by Trouffman** [comment] 2024-05-14 12:06
Duplicate of #429

**Comment by paulpv** [comment] 2024-07-21 06:08
Closing as dupe of #429

**Closed by paulpv** 2024-07-21 06:08 UTC
Labels: bug, macos, audio, old-os
