### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mikeruel** [DistroAV/DistroAV#1135] opened 2024-11-07 21:34 UTC
### Operating System Version

sequoia 15.0.1

### OBS Version

30.2.3

### OBS Installation Method

dmg

### DistroAV Version

latest

### DistroAV Installation Method

dmg

### OBS Log [URL]

https://obsproject.com/logs/6Gsss1A9x8b0M3NG

### NDI Version

can't get there

### Describe the bug

OBS error message that OBS-NDI is detected but i uninstalled it per your instructions. emptied trash. restarted several times.

### Steps to reproduce the problem

open OBS
see error message
rub forehead

**Comment by Trouffman** [comment] 2024-11-08 01:12
Please follow the instructions at : https://github.com/DistroAV/DistroAV/wiki/OBS‐NDI-Is-Now-DistroAV#macos

you still have obs-ndi in : /Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so

Closed as this is not a bug.

**Closed by Trouffman** 2024-11-08 01:12 UTC
Labels: bug, triage
