### ISSUE TITLE
[Bug]: Variable latency, changing verery 30-40 min (NDI HX3) WIN10

### ISSUE THREAD

**Issue by Maeldu83** [DistroAV/DistroAV#1018] opened 2024-05-13 09:27 UTC
### Operating System Version

Win 10

### CPU

i5 14500

### GPU

RTX 4060

### NDI Devices

PTZOptics MOVE 4K

### OBS Version

30.1.2

### OBS Installation Method

.Exe

### OBS-NDI Version

4.13.0

### OBS-NDI Installation Method

.exe

### NDI Version

5.6.1.0

### Describe the bug

When adding my NDI PTZ Cameras into OBS thanks to the plugin, when i choose latency "normal" or "reduced", this one is not consistent over time. 
I have another camera captured via hdmi filming a video syncing tool (to have a point of comparison). On the NDI cam when I reset the latency on the ndi source (because changing the latency setting resets the problem cycle) and select "normal" latency, i got 150ms latency with my other camera BUT after 30-40min the latency changes to 330ms, then after another 30-40min latency goes back to 150ms and again go back to 330ms after 30-40min and over and over again. This behaviour is the same with the "reduced" latency. 
Adding framsync doesn't change anything, hardware acceleration has no impact also. The only way of getting rid of this variable latency is to select the "lowest" latency but the image is not very smooth when doing pan/tilt moves so I'm not very satisfied by this option.

Thanks

**Comment by Trouffman** [comment] 2024-05-13 15:07
Thanks for reporting this. It this also happenning when you get it from another source (like studio monitor).
Do you have "Green ethernet" disable on you Network interface ?

**Comment by Maeldu83** [comment] 2024-05-13 20:39
Hello,
I still didn't tried to use studio monitor to see if the latency changes. I'll do it soon.
Yes my ethernet is green light 1000mbps if that's what your asking :) 

Also, do you know if having a little frame loss in the lowest latency mode is showing a problem ? I just have some little drops, it could be almost usable.

**Comment by Trouffman** [comment] 2024-05-13 20:45
Lowest latency might drop some frame in order to prioritize latency.

I was not referring to the green LED but to an advanced setting in the device manager of your NIC (network Interface) called "Green Ethernet".

This can cause lagging/stuttering like you describe when this feature is Enabled on your network device.

**Comment by Maeldu83** [comment] 2024-05-15 14:42
Ok but if we consider we have a perfect network, should the low latency mode not drop any frame ?

I don't have any "Green Ethernet" setting inside my router parameters ...

**Comment by Trouffman** [comment] 2024-05-16 01:14
The Green Ethernet option is NOT on your router but in your Windows device manager advanced options for your network interface.

Anyway.
Can you reproduce this issue on other system?
I could not reproduce this on my systems.

**Comment by Maeldu83** [comment] 2024-05-19 17:11
Ok so i had the green ethernet on my ethernet device. I deactivated it but the issue is the same (and this time the latency was growing over and over again !). In lowest latency mode, I got a very good result this time, very little frame drops, almost 100% fluid. But I still would like to use the buffer mode to avoid bad surprises ... 
I will try to test on another PC.

Also, I tried to monitor my camera thanks to NDI studio monitor and with this software, no latency changing. So I really think this issue is obs-ndi linked.

**Comment by Trouffman** [comment] 2024-05-19 22:43
Thanks for checking.

We would need a sure way to reproduce that issue.

If you can describe step by step (bullet point) how to reproduce this issue that will be welcome.

Also detail what you compare with. (Like the studio monitor on same platform etc).

This is necessary so it can be tested/reproduced (if someone has the same hardware) or tested of reproducible with other configuration.

**Comment by Maeldu83** [comment] 2024-05-26 10:51
Hello,

For information, I tested on another PC (i7, RTX2080 SUPER, WIN10, not a fresh install contrary to my production PC) and I got the exact same issue on the same version of OBS with the obs-ndi plugin. Latency is changing every 30-40min with the buffered latency setting.

I don't know what to describe, I do nothing special ... My network is composed of a router ZTE MC801A, NETGEAR PoE Switch. My PTZ camera is linked to the PoE switch with Ethernet cat7 and same for my PC.
I launch obs, set the latency of my camera to "normal (buffered)", make a window capture of a video/audio syncing tool and film my screen with my camera. I make a scene with the 2 PoVs (window capture & my camera filming my screen) and I let it run without recording or streaming. After 30-40min the latency changes and it does it again 30-40min later. If the latency has changed and I go to NDI parameters of my capture to change latency to "minimum" and go back to "normal" it resets the latency and I got the same latency as when I started the test. 

When I used studio monitor to compare, I only displayed my syncing tool video on my PC and monitor my camera filming my screen with NDI Studio monitor. There were no latency change in this case (no OBS used).

I really need to get this working ... I hope we'll find the issue. 

Thanks a lot.

**Comment by Maeldu83** [comment] 2024-06-03 18:00
Hi ! Any news about this issue ? 

Thanks a lot

**Comment by RayneYoruka** [comment] 2024-06-03 18:06
Hi my best advice is that you use NDI bridge to transcode the feed and avoid any changes in latency.. this is the general advice with HX since it doesn't play too well with obs-ndi.

https://docs.ndi.video/tools/ndi-tools-for-windows/bridge

**Comment by Maeldu83** [comment] 2024-06-12 11:46
Hi!
I tried using the NDI bridge in local mode converting my HX3 to NDI and adding the corresponding source in obs using obs-ndi plugin and I get the exact same issue. Latency is changing sometimes getting higher, sometimes lower. 

I searched a bit and I found this topic https://github.com/obs-ndi/obs-ndi/issues/851 . It seems this has been already updated in the plugin but from what I read there, I have a very very similar problem : latency issues in "normal" latency mode and very few drops using "Lowest (unbuffered)" latency mode (Like 1 frame drop every 2seconds when making large movements with my PTZ cam). 

I would really love either get rid of this latency issue or having a perfectly smooth result with the unbuffered option.

Thanks.

**Comment by Maeldu83** [comment] 2024-06-17 11:21
@Trouffman Have you seen my new messages?

**Comment by Maeldu83** [comment] 2024-06-24 11:40
Update from discord : 

OK so here's a video of the phenomenon : https://www.swisstransfer.com/d/e58d9000-bf7c-4bef-a5c8-828fb24283ea
Then, I recap : 
- I tested on 2 different PCs on the same network : same issue
- I deactivated green ethernet and gigabit lite
- I tested with studio monitor : No issues
- I tested with Vmix : no issues
- I tested with another router (microtik) : same issue
- I changed obs affinity to 4 cores : same issue
- I limited the speed of my ethernet adapter to  1gbps : same issue

Also, it's not the problem initially presented (maybe they are linked?) but here's a footage of my PTZ camera with the minimum latency (unbuffered) setting : https://www.swisstransfer.com/d/ca1403ee-12d1-463a-8341-69c0432f2cce  (watch the whole video, you can see that from the mid of the video it's perfectly smooth for a long time)
You can see that sometimes it's perfectly smooth and that frame drops are completely random. I'm still interested to use the no latency setting (but maybe focus on the latency issue with the buffer first).

**Comment by ogmkp** [comment] 2024-08-17 16:02
I think it's not a problem of NDI timing, it's a problem of buffer recalculation by OBS see: #851

**Comment by paulpv** [comment] 2024-08-17 17:07
> I think it's not a problem of NDI timing, it's a problem of buffer recalculation by OBS see: #851

@ogmkp #851 was merged 2023/11/07 https://github.com/DistroAV/DistroAV/pull/867 and should be in all releases since

**Comment by Maeldu83** [comment] 2024-08-21 13:52
Hi guys ! 
some very important news about this issue.
I tried everything, changing network parameters, formating my PC by different means, etc… (I probably made like 50 different tries changing hardware or software things) nothing have worked.

During my tries, I tested on another PC : same issue. But recently I tried again on another other PC and this time it worked without this latency shift issue (I also got it working on a Dell laptop, so 2 PCs where the plugin worked without latency issues). There where no significant common points/differences between the all the PCs. The PCs with the issue have intel CPU, gigabyte NVidia GPU, DDR4 ram. The PCs without the issue: one with amd CPU, the other with intel CPU, gigabyte GPU, DDR4 ram. 

So my final try was this one : I wanted to change my motherboard by the same brand of the one installed in the PC the plugin was working (Asus TUF for amd here).
I bought so an ASUS TUF B760m plus II for my intel i5 and changed my RAM for DDR5.
And …… this fixed the issue ! The only difference with my previous PC build was the motherboard and RAM (but this is not coming from the RAM as I tested installing the RAM of the PC with no issue on the PC that had the issue) 

conclusion: the issue is 99% coming from a hardware thing on the motherboard. So as far as I know, if you have the issue, you should get an ASUS TUF motherboard.

My wish is that these précisions will help you to find what is the real issue inside the DistroAV plugin.

Former motherboard : gigabyte B760m gaming X DDR4
New motherboard : Asus TUF b760m plus wifi II

Fell free to ask me other précisions to better understand. 

PS : I no longer has latency shift issues using « normal » latency mode but using the « lowest (unbuffered) » mode, I still have little frame drops.

Thanks

**Comment by RayneYoruka** [comment] 2024-08-21 13:56
This is really interesting finding. The setups I've been testing to and where I run NDI all the time are AMD systems with X570 Asus Strix boards.. this might be why I don't have the issues... I wouldn't be surprised if there might be something related to intel here as well

**Closed** 2024-12-18 15:46 UTC
Labels: bug, video, triage

**Comment by normen** [comment] 2025-03-12 18:45
I don't think the issue is due to specific hardware issues. It's simply a heisenbug in that it doesn't happen as often when the system has enough headroom. This is still happening in 2025 and its not specific to obs-ndi/distroav - it happens the exact same way with the gstreamer and other plugins (that allow the buffer to be disabled)
