### ISSUE TITLE
[Bug]: NDI decoder not found for HX2

### ISSUE THREAD

**Issue by pinpox** [DistroAV/DistroAV#964] opened 2024-01-18 13:10 UTC
### Operating System Version

Linux

### CPU

Intel Core i7-8550U

### GPU

Intel Core i7-8550U

### NDI Devices

Phone

### OBS Version

30.0.2

### OBS Installation Method

system's package manager

### OBS-NDI Version

4.13.0

### OBS-NDI Installation Method

system's package manager

### NDI Version

Linux 5.6.0

### Describe the bug

I'm testing obs-ndi by using the app `Stream Camera for NDI HX` on my phone and streaming to obs.

This works fine if it is set to `Full NDI`, but when trying to use `HX2 H.264` or `HX2 H.265` I get only a screen saying `NDI decoder not found`. I also tested with the "NDI HX Camera" app, which does only support the HX variant and get the same screen.

If I understood correctly, the SDK supports decoding all formats, so I assume this is a bug in obs-ndi. I would like to use the newer HX and HX2 variants of the protocol, since they are less demanding on the network.

### Steps to reproduce the problem

1. Get the `Stream Camera for NDI HX` application [from here](https://apps.apple.com/us/app/stream-camera-for-ndi-hx/id1633326432)
2. Add source in obs
3. Set the app to `Full NDI` to confirm it works
4. Set the app to any of the other HX options and see how it does no longer work

### Expected behavior

HX variants of the NDI protocol are decoded just as the Full NDI version works

### Screenshots

![image](https://github.com/obs-ndi/obs-ndi/assets/1719781/6c3f665d-1650-4b0e-ab20-9edbd427c6a6)
![image](https://github.com/obs-ndi/obs-ndi/assets/1719781/4e13a40d-2c8b-44f0-a848-7bc874e9b550)
![image](https://github.com/obs-ndi/obs-ndi/assets/1719781/71d4c5bf-8aa4-4da2-8a73-c0d9747343ae)

**Comment by paulpv** [comment] 2024-01-18 16:16
Duplicate of https://github.com/obs-ndi/obs-ndi/issues/951

What version of Linux?
What version of avahi and ffmpeg?

Try the following commands:
```
sudo apt install avahi-daemon ffmpeg
sudo systemctl enable avahi-daemon
sudo systemctl start avahi-daemon
sudo ufw allow 5353/udp
sudo ufw allow 5959:5969/tcp
sudo ufw allow 5959:5969/udp
sudo ufw allow 6960:6970/tcp
sudo ufw allow 6960:6970/udp
sudo ufw allow 7960:7970/tcp
sudo ufw allow 7960:7970/udp
sudo ufw allow 5960/tcp
```

**Comment by paulpv** [comment] 2024-01-18 17:06
The standard NDI SDK can decode HX fine on Windows.
Ubuntu 22 can decoding HX fine, but since other versions are having problems.
Unknown why.
It seems to need more libraries that are not automatically included in any install of the base OS, OBS, obs-ndi, or NDI.

Please run this command in the /usr/local/lib/ folder:
`strings libndi.so.5.6.0 | grep "\.so[.0-9]*$"`

Advanced is not needed to decode HX.

> What SDK is used when installing through homebrew on mac?
Installing what? OBS? I am not aware of any brew installer for obs-ndi or NDI.

**Comment by pinpox** [comment] 2024-01-18 20:50
> Please run this command in the /usr/local/lib/ folder:

I changed the path for nix, but this is the output you asked:

```
❯ strings /nix/store/6h79i7zvd60jngxj4g699sa0z61x1cc7-ndi-5.6.0/lib/libndi.so.5 | grep "\.so[.0-9]*$"
libndihx.so
libavcodec.so.58
libavcodec-ndi.so.58
libavutil.so.56
libavutil-ndi.so.56
libmsquic.lttng.so.2.1.9
libavahi-common.so.3
libavahi-client.so.3
libdl.so.2
libm.so.6
libpthread.so.0
libc.so.6
ld-linux-x86-64.so.2
libndi.so.5
```

> The standard NDI SDK can decode HX fine on Windows.
> Ubuntu 22 can decoding HX fine, but some other versions are having problems.

Interesting, thanks for explaining. Just to confirm I tested the same app and versions on a windows machine and can confirm it works for me aswell on windows. 

> Installing what? OBS? I am not aware of any brew installer for obs-ndi or NDI. 

I'm not an export on mac, but I assume this is the homebrew installer for it: https://github.com/Homebrew/homebrew-cask/blob/7f1e0ae7f30c291512da241458c8aa0dc5b9357a/Casks/l/libndi.rb

**Comment by paulpv** [comment] 2024-01-18 23:56
What does MacOS have to do with your setup?
You do not mention Mac in your original bug.

**Comment by pinpox** [comment] 2024-01-19 03:24
Sorry for the confusion, my setup has nothing to do with mac, I just was trying to see what SDK is used on mac because it works there.

**Comment by paulpv** [comment] 2024-01-19 13:49
No problem, and no problem discussing semi but not directly related things.

I noticed this official NDI snippet today:
https://docs.ndi.video/docs/sdk/11.-platform-considerations#linux

**Comment by pinpox** [comment] 2024-01-19 21:12
> I noticed this official NDI snippet today:
> https://docs.ndi.video/docs/sdk/11.-platform-considerations#linux

The libraries seem to be found correctly on my system:

```
ldd /nix/store/9x79k9iz4zp9gkgjy2mlifxnknx8arc6-ndi-5.5.2/lib/libndi.so.5.6.0
        linux-vdso.so.1 (0x00007ffcabbdc000)
        libavahi-common.so.3 => /nix/store/7d5009baak8jcfcynj3y202pfq521id0-avahi-0.8/lib/libavahi-common.so.3 (0x00007f2
14ce5e000)
        libavahi-client.so.3 => /nix/store/7d5009baak8jcfcynj3y202pfq521id0-avahi-0.8/lib/libavahi-client.so.3 (0x00007f2
14ce4b000)
        libdl.so.2 => /nix/store/p3jshbwxiwifm1py0yq544fmdyy98j8a-glibc-2.38-27/lib/libdl.so.2 (0x00007f214ce46000)
        libm.so.6 => /nix/store/p3jshbwxiwifm1py0yq544fmdyy98j8a-glibc-2.38-27/lib/libm.so.6 (0x00007f214b11e000)
        libpthread.so.0 => /nix/store/p3jshbwxiwifm1py0yq544fmdyy98j8a-glibc-2.38-27/lib/libpthread.so.0 (0x00007f214ce41000)
        libc.so.6 => /nix/store/p3jshbwxiwifm1py0yq544fmdyy98j8a-glibc-2.38-27/lib/libc.so.6 (0x00007f214af35000)
        /nix/store/p3jshbwxiwifm1py0yq544fmdyy98j8a-glibc-2.38-27/lib64/ld-linux-x86-64.so.2 (0x00007f214ce6f000)
        libssp.so.0 => /nix/store/4zp05qkzh9s3c3k7pp9d36vhiz3x8h9l-gcc-13.2.0-lib/lib/libssp.so.0 (0x00007f214ce3a000)
        libdbus-1.so.3 => /nix/store/1n4yiax2bfz17j0gcm3c0xfxigd4rb2s-dbus-1.14.10-lib/lib/libdbus-1.so.3 (0x00007f214aede000)
        libsystemd.so.0 => /nix/store/dgz38k9ghdkk2q7xbzilsy4bqn4rrjk6-systemd-minimal-254.6/lib/libsystemd.so.0 (0x00007f214add1000)
        libcap.so.2 => /nix/store/jadwbh59lbmsm7l67aj971kry4ywi2c9-libcap-2.69-lib/lib/libcap.so.2 (0x00007f214ce2c000)
```
Also the avahi service is running:

```
❯ systemctl status avahi-daemon.service
● avahi-daemon.service - Avahi mDNS/DNS-SD Stack
     Loaded: loaded (/etc/systemd/system/avahi-daemon.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-01-18 12:05:46 CET; 1 day 10h ago
TriggeredBy: ● avahi-daemon.socket
   Main PID: 120432 (avahi-daemon)
     Status: "Server startup complete. Host name is ahorn.local. Local service cookie is 4015447204."
         IP: 1.2M in, 79.1K out
         IO: 13.3M read, 392.0K written
      Tasks: 1 (limit: 28538)
     Memory: 1.3M
        CPU: 1.546s
     CGroup: /system.slice/avahi-daemon.service
             └─120432 "avahi-daemon: running [ahorn.local]"
```

**Comment by paulpv** [comment] 2024-01-19 21:22
Yup! It's a mystery! Would love to know why it isn't working. That error message is coming from NDI, not us, so as far as I can tell it really is their bug to support/fix.

**Comment by paulpv** [comment] 2024-01-19 21:28
What is `nix`? (Other than short for Unix)

Is it a distro like Flatpak?

Maybe it is acting like Flatpak does?

Flatpak was unable to load files from outside of its sandbox, so libndi and avahi had to be inside the obs-ndi Flatpak.

https://github.com/obs-ndi/obs-ndi/issues/724 is quite detailed about the non-trivial work that tytan652 had to do to get it to work.

**Closed** 2024-12-18 03:07 UTC
Labels: bug, triage
