### ISSUE TITLE
Program tally light not working, preview light switched.

### ISSUE THREAD

**Issue by unknowndomain** [DistroAV/DistroAV#390] opened 2020-01-23 22:54 UTC
I have been testing this with a BirdDog Mini, the device works well although there is some delay on the tally lights sometimes.

There is an issue that the preview (green) tally light works but is showing for program (red), and the program light is never showing.

I have tested with a software source that is able to emulate the tally lights and it works well for these.

**Comment by jwetzell** [comment] 2020-07-13 20:07
I think this would be related to issue #318

**Comment by Trouffman** [comment] 2024-12-08 19:44
This cannot be fixed unless there is a major rewrite.

The tally is : use on PGM = red. Vsibled anywhere elses (display/preview/ etc) green.
Closing  as it's a duplicate of a more recent and better documented issue : #1036 & #1083

**Closed by Trouffman** 2024-12-08 19:44 UTC
Labels: needs-investigation
