### ISSUE TITLE
[Bug]: Does not work with portable OBS Studio

### ISSUE THREAD

**Issue by Mikeileech** [DistroAV/DistroAV#935] opened 2023-11-22 06:51 UTC
### Operating System Version

Windows 10

### OBS Version

29.1.3

### NDI Tools Version

4.13 (latest)

### Describe the bug

I can't figure out how to install this plugin to portable version of OBS instance

### Expected behavior

i've expected it will work after standard installation procedure, but it didn't

**Comment by paulpv** [comment] 2023-11-22 08:02
https://github.com/obs-ndi/obs-ndi#requirements
> Requirements
> OBS >= 30.0.0 (Qt6 & x64)

You are running OBS 29.1.3.
obs-ndi will not run on OBS 29.1.3.
obs-ndi requires OBS >= 30.0.0.

**Comment by WizardCM** [comment] 2023-11-22 11:16
I can confirm in a portable installation on Windows that the installer doesn't seem to copy over the files correctly (they just silently vanish), and if you do manage to copy over the files, it can't find the NDI Runtime.

**Comment by paulpv** [comment] 2023-11-22 12:12
What version of portland OBS?

**Comment by Trouffman** [comment] 2024-11-17 05:51
Been using this in portable install a lot. Could not reproduce. Closing (fall 2024 cleanup)

**Closed** 2024-11-17 05:50 UTC
Labels: bug, Installation
