### ISSUE TITLE
Issue with the Filter "Videodelay (async)"

### ISSUE THREAD

**Issue by djmisky** [DistroAV/DistroAV#956] opened 2024-01-08 17:49 UTC
Hey,

i got a new PTZ Camera the Obsbot "Tail Air".
when i try to activate the filter "Videodelay (async)" the delay is 10 seconds! not milliseconds.

i verified the problem on different OBS (28-30) and Plugin Versions and on 3 differnt Windows PCs.
Its always the same. 

With other NDI Cameras there is no problem like this.

my current workaround is to run a second OBS and send the signal to the NDI Main output and get this in my "normal" Streaming OBS installation.

can you help me?

_Originally posted by @djmisky in https://github.com/obs-ndi/obs-ndi/discussions/955_

**Comment by paulpv** [comment] 2024-01-25 01:12
Duplicate of #955

**Comment by paulpv** [comment] 2024-01-25 01:13
Weird! No! 955 is just a discussion at https://github.com/obs-ndi/obs-ndi/discussions/955
Re-opening.

**Comment by paulpv** [comment] 2024-01-25 01:16
I got my OBSBOT Tail Air last week and was busy and just now got a chance to fire it up and connect it to my mac OBS+obsndi.

It fired up and worked just fine as an NDI transmitter and OBS+obsndi acting as a Virtual Camera in meetings.

I will next look into your reported `Videodelay (async)` delay problem.

**Comment by paulpv** [comment] 2024-01-25 01:18
After a few minutes I do see the latency of the video in OBS being over a second behind the OBSBOT app preview.

**Comment by djmisky** [comment] 2024-01-25 06:13
In my setup the issue appears immediately. I only use 10ms latency but I got 10 full seconds

**Comment by djmisky** [comment] 2024-02-21 17:39
any news

**Comment by djmisky** [comment] 2024-03-23 18:42
@paulpv Any News?

**Comment by Trouffman** [comment] 2024-12-18 02:59
@djmisky this project is maintained and support solely by volunteers.

It is hard to reproduce without the hardware.

As new requirement and version have been released. Please follow the new step to report the issue on the latest versions.

Thank you for reporting this.

**Closed by Trouffman** 2024-12-18 02:59 UTC
